<a href="https://colab.research.google.com/github/tu22014/EU_M_Math-Repository/blob/main/chap02_Ex05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点第3位まで表示
%precision 3

#(2-5)
#　線形代数用のライブラリ
import scipy.linalg as linalg

#行列の入力
practice2_5 = np.array([[1, 2, 3],
                       [1, 3, 2],
                       [3, 1, 2]])
#逆行列
print('逆行列:', linalg.inv(practice2_5))

#固有値と固有ベクトル
practice2_5_value, practice2_5_vecter = linalg.eig(practice2_5)
#固有値
print('固有値:', practice2_5_value)

#固有ベクトル
print('固有ベクトル:', practice2_5_vecter)

逆行列: [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値: [ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル: [[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]
