<a href="https://colab.research.google.com/github/tu22014/EU_M_Math-Repository/blob/main/chap02_Ex03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点第3位まで表示
%precision 3

#(2-3)
#要素がすべて3の5行5列
practice2_3 = np.array([3 for i in range(25)]).reshape(5, 5)
#行列の２乗
print(practice2_3.dot(practice2_3))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
